ln -fs ~/dotfiles/.w3m ~/.w3m
ln -fs ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -fs ~/dotfiles/.gitconfig ~/.gitconfig
ln -fs ~/dotfiles/.latexmkrc ~/.latexmkrc
ln -fs ~/dotfiles/.zshrc ~/.zshrc
ln -fs ~/dotfiles/.fzf.bash ~/.fzf.bash
ln -fs ~/dotfiles/.fzf.zsh ~/.fzf.zsh
ln -sf ~/dotfiles/.config/libskk ~/.config/libskk/
ln -sf ~/dotfiles/.config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
ln -sf ~/dotfiles/.config/almel/almel.yaml ~/.config/almel/almel.yml
